/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_ctmfile_free(a: number): void;
export function ctmfile_vertices_ptr(a: number): number;
export function ctmfile_vertices_len(a: number): number;
export function ctmfile_normals_ptr(a: number): number;
export function ctmfile_normals_len(a: number): number;
export function ctmfile_indices_ptr(a: number): number;
export function ctmfile_indices_len(a: number): number;
export function ctmfile_uvs_ptr(a: number): number;
export function ctmfile_uvs_len(a: number): number;
export function ctmfile_colors_ptr(a: number): number;
export function ctmfile_colors_len(a: number): number;
export function create_ctm_file(a: number, b: number): number;
export function __wbg_stream_free(a: number): void;
export function stream_get_position(a: number): number;
export function stream_set_position(a: number, b: number): void;
export function stream_get_ptr(a: number): number;
export function stream_read_i8(a: number): number;
export function stream_read_i16(a: number): number;
export function stream_read_i32(a: number): number;
export function stream_read_u8(a: number): number;
export function stream_read_u16(a: number): number;
export function stream_read_u32(a: number): number;
export function stream_read_f32(a: number): number;
export function stream_read_f64(a: number): number;
export function stream_unpack30(a: number): number;
export function stream_read_bool(a: number): number;
export function stream_read_str(a: number, b: number): void;
export function stream_read_nano_str(a: number, b: number): void;
export function stream_read_cstr(a: number, b: number): void;
export function stream_match_dex_magic(a: number, b: number): number;
export function create_stream(a: number, b: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
